### ISSUE TITLE
Downloads `.txz.sha256` file from SlackOnly

### ISSUE THREAD

**Issue by KnifeFed** [ich777/un-get#10]
I added `https://slackonly.com/pub/packages/15.0-x86_64/ SlackOnly` and when trying to install [fzf](https://slackonly.com/pub/packages/15.0-x86_64/system/fzf/) I get this:

```sh
$ un-get search fzf
Please wait, performing search...
Found the following package(s) for your search 'fzf' in repositories:
fzf-0.29.0
fzf-0.29.0

$ un-get install fzf
The following package(s) will be installed: fzf
Are you sure? [y/N] y

     0K                                                      100%  237M=0s

Cannot install fzf-0.29.0-x86_64-1_slonly.txz.sha256: invalid package extension
```

It downloads and tries to install the `.sha256` file instead of the `.txz` file. I don't know if this repo adheres to the Slackware standard but it would be nice if un-get could ignore the `.sha256` file and get the `.txz` file instead.

Also, the package is listed twice in the search as you can see. It's not available in any of the other repos.

**Comment by ich777** [comment]
@KnifeFed thank you for the report. I pushed an update to `un-get` `v0.21`, please update the plugin to `2023.02.02`.

If you experience any further issues feel free to open up a new issue, if this issue is resolved for you please close the issue.

**Comment by KnifeFed** [comment]
Thanks, works great now! Also, a huge thank you for creating un-get!
