### ISSUE TITLE
iotop?!

### ISSUE THREAD

**Issue by luckyheiko** [ich777/un-get#11]
ich habe mit un-get das iotop instaliert

und trotz neustart des Unraid, bekomme ich iotop nicht zum starten
![1](https://user-images.githubusercontent.com/26415601/229307390-70c30728-ac23-4d2a-abd6-c062aa0b8f9d.png)

ist da ein fehler meinerseits?
oder muss ich bei un-get was spezielles machen?

**Comment by ich777** [comment]
Please only in English over here.

You are missing `python3`.
`iotop` version `0.6` requires Python too IIRC.

-----------------------------------------------------------------------------

Deutsch, du must für `iotop` in der version `0.6` zusätzlich noch `python3` instllieren soweit ich weiß da es ohne das nicht funktionieren wird.

**Comment by ich777** [comment]
Closing due to no response.
@luckyheiko feel free to reopen the issue if you are experiencing further issues.
