### ISSUE TITLE
[Feature] Add `-y` Option to "un-get install"

### ISSUE THREAD

**Issue by mirisbowring** [ich777/un-get#19]
Hi it would be great to have an `-y` option on the `install` argument (similar to `apt-get`).

Problem I am facing:
When Un-Get is run during start (to install some packages), it is not successfull since it asks the user to [y/N] on an install command.

By providing such flag Un-Get would know that I definetely want to install it without user interaction.

**Comment by ich777** [comment]
Please look at #12

**Comment by mirisbowring** [comment]
oh sry - missed this one, thanks!
