### ISSUE TITLE
bluetoothd didnit start on boot

### ISSUE THREAD

**Issue by VergilGao** [ich777/un-get#3]
after a reboot, i called `bluetoothctl`
```
$ bluetoothctl
Waiting to connect to bluetoothd...
```
then, i start the bluetooth manually
```
$ /etc/rc.d/rc.bluetooth start
Starting Bluetooth services:  bluetoothd hciconfig sdptool hciattach
$ bluetoothctl
Agent registered
[CHG] Controller **** Pairable: yes
[CHG] Controller **** Discovering: yes
[NEW] Device ****
[NEW] Device ****
[NEW] Device ****
[NEW] Device ****
[NEW] Device ****
[NEW] Device ****
[bluetooth]#
```

i think i can use user-scripts to call `/etc/rc.d/rc.bluetooth start` to fix it.

**Comment by ich777** [comment]
@VergilGao this is just default behavior on Unraid because the package is installed after the rc.bluetooth would kick in, that's why it doesn't start automatically.

You don't need a user-script, just put something like this in your `go` file (before emhttp is started):
```
# Start Bluetooth
/etc/rc.d/rc.bluetooth start
```
and you should be good to go.

**Comment by VergilGao** [comment]
another problem
ncurses must install before tmux, is there any way to ensure it ?

**Comment by ich777** [comment]
The packages are usually installed in alphabetical order and in this specific case this should not be an issue.
But when installing the packages is it really that important?
On Slackware or better speaking in `un-get` is no dependency check in place and even if something is missing that prevents `tmux` from running it should be also safe to install `ncurses` after `tmux` as long as nothing is calling `tmux` in the meantime or does the `tmux` package modify something that is installed with `ncurses`?

**Comment by VergilGao** [comment]
>   Do you know that ncurses v6.3 comes pre-installed with Unraid 6.11.1?

sorry about that

i found my TERM variable was `screen` in tmux, thats the reason.

**Comment by ich777** [comment]
Glad that you got it solved. :smiley: 

Anyways, on Slackware or at least with `un-get` it should be no issue since there is no dependency checking in place and even if a package is installed which depends on a package which is installed later it should be no issue.

Can this issue then be closed?

**Comment by VergilGao** [comment]
> Glad that you got it solved. 😃
> 
> Anyways, on Slackware or at least with it should be no issue since there is no dependency checking in place and even if a package is installed which depends on a package which is installed later it should be no issue.`un-get`
> 
> Can this issue then be closed?

thank you. i will close this issue.
