### ISSUE TITLE
Checksum check doesn't always work

### ISSUE THREAD

**Issue by robertklep** [ich777/un-get#4]
I tried to install `vim` but got an error about a checksum mismatch.

The reason turned out that the grep [on this line](https://github.com/ich777/un-get/blob/c6ec2c99447936f78750e658b3c8ac28518631b8/source/usr/local/emhttp/plugins/un-get/un-get#L98) returns two matches:
```
1912520cf24892a77371139fd350810f  ./ap/vim-8.2.4256-x86_64-1.txz
21ff847449660ba8661db405c4520cdf  ./xap/vim-gvim-8.2.4256-x86_64-1.txz
```
(the package I'm trying to install is `vim-8.2.4256-x86_64-1.txz`, which also matches `vim-gvim-8.2.4256-x86_64-1.txz`)

I fixed it by also matching the preceding slash: `grep "/$1"`

**Comment by ich777** [comment]
@robertklep thank you for the report, please update the plugin to `v0.17`/`2022-10-12`, already released a fix!

If you got any further issues please feel free to re-open the issue or create a new one.

**Comment by robertklep** [comment]
@ich777 whoops, sorry for the noise!

**Comment by ich777** [comment]
@robertklep oh sorry, maybe my language barrier kicked in.
Released a fix based on your report is what I wanted to say...

**Comment by robertklep** [comment]
@ich777 😅 in any case, thanks!
